FROM node:carbon

ENV PORT $PORT
ENV GOOGLE_CLIENT_ID $GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET $GOOGLE_CLIENT_SECRET
ENV GOOGLE_CALLBACK $GOOGLE_CALLBACK
ENV FACEBOOK_CLIENT_ID $FACEBOOK_CLIENT_ID
ENV FACEBOOK_CLIENT_SECRET $FACEBOOK_CLIENT_SECRET
ENV FACEBOOK_CALLBACK $FACEBOOK_CALLBACK
WORKDIR /usr/src/app

COPY . .

RUN npm install --production

EXPOSE $PORT

CMD ["npm", "start"]
